# mail.ftl — FreeSynergy Stalwart Mail Manager (English)

# ── Navigation ────────────────────────────────────────────────────────────────

mail-wizard-nav-setup = Setup
mail-wizard-nav-dns   = DNS Records

# ── Step titles ───────────────────────────────────────────────────────────────

mail-wizard-step-domain-title = Mail Domain
mail-wizard-step-tls-title    = TLS Certificates
mail-wizard-step-oidc-title   = Identity Provider (OIDC)
mail-wizard-step-confirm-title = Review & Confirm
mail-wizard-step-done-title   = Setup Complete

# ── Step descriptions ─────────────────────────────────────────────────────────

mail-wizard-step-domain-desc = Enter the primary mail domain and postmaster address (e.g. mail.example.com / admin@example.com).
mail-wizard-step-tls-desc = Choose between automatic TLS via ACME (Let's Encrypt) or provide your own certificate and key files.
mail-wizard-step-oidc-desc = Connect Stalwart to Kanidm for user authentication via OIDC. Users log in with their FreeSynergy account. This step is optional.
mail-wizard-step-confirm-desc = Review your configuration before writing it to disk and starting the Stalwart container.
mail-wizard-step-done-desc = Stalwart Mail has been configured successfully. Set the required DNS records shown below before your domain can send and receive mail.

# ── Field labels ──────────────────────────────────────────────────────────────

mail-wizard-field-domain      = Domain
mail-wizard-field-admin-email = Admin / Postmaster
mail-wizard-field-tls         = TLS
mail-wizard-field-oidc        = Identity Provider
mail-wizard-field-not-set     = (not set)
mail-wizard-current-step      = Current step

# ── TLS ───────────────────────────────────────────────────────────────────────

mail-wizard-tls-acme   = ACME (automatic — Let's Encrypt)
mail-wizard-tls-manual = Manual certificate

# ── OIDC ─────────────────────────────────────────────────────────────────────

mail-wizard-oidc-skipped = Skipped (local accounts only)

# ── Form placeholders ─────────────────────────────────────────────────────────

mail-wizard-domain-placeholder       = e.g. mail.example.com
mail-wizard-admin-email-placeholder  = e.g. admin@example.com
mail-wizard-cert-path-placeholder    = /etc/freesynergy/stalwart/cert.pem
mail-wizard-key-path-placeholder     = /etc/freesynergy/stalwart/key.pem
mail-wizard-oidc-issuer-placeholder  = e.g. https://idm.example.com
mail-wizard-oidc-client-placeholder  = e.g. stalwart
mail-wizard-oidc-secret-placeholder  = Client secret

# ── Buttons ───────────────────────────────────────────────────────────────────

mail-wizard-btn-next      = Next
mail-wizard-btn-skip-oidc = Skip (local accounts)
mail-wizard-btn-confirm   = Apply Configuration
mail-wizard-btn-use-acme  = Use ACME (recommended)
mail-wizard-btn-use-manual = Use manual certificate

# ── DNS hints ─────────────────────────────────────────────────────────────────

mail-wizard-dns-mx-hint    = MX  — Point your MX record at this server's hostname
mail-wizard-dns-spf-hint   = SPF — Add: v=spf1 mx ~all
mail-wizard-dns-dkim-hint  = DKIM — Generated by Stalwart on first start; add to DNS
mail-wizard-dns-dmarc-hint = DMARC — Add: v=DMARC1; p=none; rua=mailto:admin@{$domain}
mail-wizard-dns-note       = Note: DNS propagation may take up to 48 hours.

# ── Error messages ────────────────────────────────────────────────────────────

mail-wizard-error-domain-empty          = Domain must not be empty.
mail-wizard-error-domain-spaces         = Domain must not contain spaces.
mail-wizard-error-admin-email-invalid   = A valid e-mail address is required (must contain @).
mail-wizard-error-tls-paths-empty       = Both certificate and key paths are required for manual TLS.
mail-wizard-error-tls-required          = TLS must be configured (ACME or manual) before proceeding.
mail-wizard-error-oidc-fields-required  = Issuer URL, client ID, and client secret are all required.
mail-wizard-error-oidc-required         = Configure OIDC or press Skip to use local accounts.
mail-wizard-error-domain-required       = Domain and postmaster address are required.
mail-wizard-error-config-incomplete     = Configuration is incomplete — check all previous steps.
mail-wizard-error-wrong-step            = This action is not available at the current step.
mail-wizard-error-skip-invalid-step     = Skip is only available on the OIDC step.

# ── Status / events ───────────────────────────────────────────────────────────

mail-adapter-registered   = Stalwart Mail adapter registered in fs-registry.
mail-adapter-deregistered = Stalwart Mail adapter deregistered from fs-registry.
